By Rahul kumar

github - https://github.com/Rahul5914

youtube - https://youtube.com/@biharwaleenginner?si=n-b4mPbcUZ35wt7P

linkedin - https://www.linkedin.com/in/rahul-kumar-3829b322a/

instagram - @therahul5914

NumPy - Numerical Python

Advantages of Numpy Arrays:

1. Allows several Mathematical Operations
2. Faster operations

*Key Features and Use Cases:*

**N-dimensional arrays**: -NumPy's primary data structure is the ndarray, a powerful multi-dimensional array object.

**Mathematical Operations**:- NumPy offers a wide range of functions for performing mathematical operations on arrays, including element-wise operations, linear algebra, Fourier transforms, and statistical function

**Data Analysis and Scientific Computing:-**It's widely used in data analysis, machine learning, and other scientific computing applications

**Efficiency:**- NumPy arrays are designed for efficiency, offering significant speed advantages over standard Python lists when performing numerical computation





import the library using  **import numpy as np**

**Creating Arrays:** create NumPy arrays from Python lists or other iterable objects using np.array()

**Array Attributes:** NumPy arrays have attributes like shape (number of dimensions and size of each dimension), dtype (data type of elements), and ndim (number of dimensions

**Indexing and Slicing:**access elements of NumPy arrays using indexing and slicing, similar to Python lists

**install NumPy using pip: pip install numpy**

In [2]:
import numpy as np

List vs Numpy - Time Taken

In [3]:
from time import process_time

Time taken by a list

In [4]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.001209346


In [5]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)

0.00032044600000036283


Numpy Arrays

In [6]:
# list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [7]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [8]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
a.shape

(4,)

In [10]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [11]:
b.shape

(2, 4)

In [12]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [13]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
# create a numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [16]:
# create an identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.80945881 0.08492365 0.96708859 0.33213636]
 [0.96989669 0.02115365 0.79058124 0.1868766 ]
 [0.89761938 0.70955488 0.68117627 0.82507369]]


In [18]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[96 86 37 81 39]
 [72 68 16 60 51]
 [25 32 73 10 70]]


In [19]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [20]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [21]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array

In [22]:
c = np.random.randint(10,90,(5,5))
print(c)

[[47 77 32 11 84]
 [58 51 39 76 57]
 [39 86 23 71 30]
 [12 78 25 50 71]
 [12 25 27 63 20]]


In [23]:
# array dimension
print(c.shape)

(5, 5)


In [24]:
# number of dimensions
print(c.ndim)

2


In [25]:
# number of elements in an array
print(c.size)

25


In [26]:
# checking the data type of the values in the array
print(c.dtype)

int64


Mathematical operations on a np array

In [27]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [28]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [29]:
print(a)
print(b)

[[2 6 1]
 [2 0 8]
 [1 3 6]]
[[17 13 12]
 [12 19 15]
 [19 14 18]]


In [30]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[19 19 13]
 [14 19 23]
 [20 17 24]]
[[-15  -7 -11]
 [-10 -19  -7]
 [-18 -11 -12]]
[[ 34  78  12]
 [ 24   0 120]
 [ 19  42 108]]
[[0.11764706 0.46153846 0.08333333]
 [0.16666667 0.         0.53333333]
 [0.05263158 0.21428571 0.33333333]]


In [31]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [32]:
print(a)
print(b)

[[7 9 8]
 [5 4 4]
 [7 4 3]]
[[15 14 19]
 [19 10 17]
 [14 19 13]]


In [33]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[22 23 27]
 [24 14 21]
 [21 23 16]]
[[ -8  -5 -11]
 [-14  -6 -13]
 [ -7 -15 -10]]
[[105 126 152]
 [ 95  40  68]
 [ 98  76  39]]
[[0.46666667 0.64285714 0.42105263]
 [0.26315789 0.4        0.23529412]
 [0.5        0.21052632 0.23076923]]


Array Manipulation

In [34]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 4 4]
 [8 3 7]]
(2, 3)


In [35]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[7 8]
 [4 3]
 [4 7]]
(3, 2)


In [36]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[8 8 2]
 [2 2 7]]
(2, 3)


In [37]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[8 2]
 [8 2]
 [2 7]]
(3, 2)


In [38]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[4 2 1]
 [3 8 9]]
(2, 3)


In [39]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[4 2]
 [1 3]
 [8 9]]
(3, 2)
